char *Help = "\n"
"[36mNAME[0m\n"
"    nntrain - nn4cc training app\n"
"\n"
"[36mUSAGE[0m\n"
"    nntrain [[36mOPTIONS[0m] [36mDATAFILES[0m...\n"
"\n"
"[36mDESCRIPTION[0m\n"
"    Nntrain loads data files and trains the neural network on the training\n"
"    set, while simultaneously evaluating performance on testing sets in\n"
"    [36mlog-scheduled[0m time steps.  Now compiled for [36m__TOPOLOGY__[0m neural networks.\n"
"\n"
"    Data files should be in the [36mSSV[0m form.  First inputs columns, then\n"
"    outputs columns, then ignored data until the end of line.  Hash\n"
"    delimited comments are ignored.  Filenames are either [36mtrain.dat[0m,\n"
"    [36mtest.dat[0m, [36mtest1.dat[0m and [36mtest2.dat[0m, or any names with role specified\n"
"    by the [36m-train[0m and [36m-test[0m options.\n"
"\n"
"    Training output is saved into the [36m./Log/[0m directory.\n"
"\n"
"[36mOPTIONS[0m\n"
"             [36m-h[0m  This help.\n"
"             [36m-v[0m  Extra verbose mode.\n"
"             [36m-q[0m  Quiet recompilation.\n"
"            [36m-np[0m  No progress report.\n"
"\n"
"        [36m-n [36mNAME[0m[0m  Sets the experiment name for logdir and journal.log.\n"
"                 Patterns [36m%d[0m,[36m%t[0m are formatted to datetime and topology.\n"
"                 If no [0mNAME[0m is specified the datetime is used.\n"
"         [36m-train[0m  All data files after this switch will be a training set.\n"
"          [36m-test[0m  Following files are testing set (alias [36m-test1[0m).\n"
"         [36m-test2[0m  Following files are alternative testing set.\n"
"\n"
"         [36m-e NUM[0m  The number of training epochs/cycles (default no limit),\n"
"      [36m-secs NUM[0m  or the desired length of the training in seconds,\n"
"      [36m-pats NUM[0m  or the desired number of patterns to train.  Whichewer will\n"
"                 happen first.  Decimal values for epochs or secs are accepted.\n"
"\n"
"         [36m-g NUM[0m  Learning rate, gamma (default 0.08).\n"
"    [36m-t [36mTOPOLOGY[0m[0m  Topology (current is [36m__TOPOLOGY__[0m).\n"
"\n"
"         [36m-p NUM[0m  The number of testing threads running in parallel.\n"
"         [36m-s NUM[0m  Logarithmic scheduler step multiplier (default 1.3).\n"
"                 Inputs 20% or 0.2 are converted to the 1.2 multiplier.\n"
"            [36m-dt[0m  Deterministic tests order (default is random order).\n"
"\n"
"            [36m-E0[0m  No errors logging.\n"
"            [36m-E1[0m  Default, aggregated [0mMAE[0m and its per-pat min/max log.\n"
"            [36m-E2[0m  Advanced errors log with MSE, distance, per output MAEs\n"
"                 and complete outputs logs.\n"
"            [36m-E3[0m  Median-type errors.\n"
"            [36m-W0[0m  Don't log weights.\n"
"            [36m-C1[0m  Log credits, simple input weights aggregates.\n"
"\n"
"[36mTOPOLOGY[0m\n"
"        [36m10-30-3[0m  10 inputs, 30 hiden neurons, 3 outputs.\n"
"      [36m4-2sigm-3[0m  4 inputs, 2 sigmoidal hidden, 3 (default sigm.) outputs.\n"
"   [36m5-2r-3s-4r-6[0m  5 inputs, 2 relu, 3 sigm., 4 relu, 6 default sigm.\n"
"\n"
"[36mSTOP[0m\n"
"  [36msingle Ctrl-C[0m  Finish current error evaluations and stop.\n"
"  [36mdouble Ctrl-C[0m  Close all error evaluations and stop.\n"
"                 Queued, but not started evaluations will be lost anyway.\n"
"\n"
"[36mEXAMPLE[0m\n"
"    [37mnntrain -g 0.1 -name 1st_experiment train.dat[0m\n"
"\n"
"[36mSEE ALSO[0m\n"
"    [37merplot -h[0m\n"
"\n"
"[36mVERSION[0m\n"
"    nn4cc-0.2 (c) R.Jaksa 2019, GPLv3\n"
"\n";
